name: LaTeX build

on:
  schedule:
    - cron: '21 15 * * *'
  push:
  pull_request:

jobs:
  tex:
    runs-on: ubuntu-latest
    name: "Build LaTeX"
    container:
      image: thomasweise/texlive
    steps:
      - name: Build
        run: make pdf/cv.pdf
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            pdf/cv.pdf
